### ISSUE TITLE
Babel

### ISSUE THREAD

**Issue by sollerias** [hexlet-boilerplates/nodejs-package#33]
Ребята, доброго времени суток!

Подскажите, пожалуйста, если не секрет, куда делся Babel и за что его удалили? Я в шоке. Очень интересует данный инцидент.

**Comment by mokevnin** [comment]
Теперь работает без бабеля) Нативные модули + поддержка от jest

**Comment by sollerias** [comment]
Спасибо! Вот это поворот! Прочитал информацию по этой теме. А я правильно понимаю, что нужно использовать версию от 14.2.0? Для версии 14.0.0 разработчики писали ([Ссылочка на документацию](https://nodejs.org/en/blog/release/v14.0.0/)):

> As of Node.js 14 there is no longer this warning when using ESM in Node.js. However, the ESM implementation in Node.js remains experimental. As per our stability index: “The feature is not subject to Semantic Versioning rules. Non-backward compatible changes or removal may occur in any future release.” Users should be cautious when using the feature in production environments.

Мол, будьте осторожны при работе в продакшене. Стоит ли на эту тему беспокоиться или вы это уже у себя используете и всё огонь?

**Comment by mokevnin** [comment]
Это стандартная отписка. Могут все поменять. Но это ведь происходит не во время использования, а во время обновления ноды. А этот процесс мы контролируем)

**Comment by sollerias** [comment]
Не знал про такие стандартные предупреждения. То есть, в продакшене юзать можно? А то я уже во Слаке этот вопрос написал.

**Comment by mokevnin** [comment]
Я имею ввиду что это стандартно для индустрии. Так всегда вводят вещи, которые потом могут поменяться. Мол завязывайтесь на свой страх и риск. Это не значит что фича бажная, это значит что будьте готовы переписать код если мы ее поменяем.

А использовать можно.

**Comment by sollerias** [comment]
А вот это, кстати, очень важное замечание:

> Это не значит что фича бажная, это значит что будьте готовы переписать код если мы ее поменяем.

Потому что мне, как раз, первое, что пришло в голову, - это то, что есть какие-то баги с этим модулем. 

Большое спасибо за разъяснение, теперь буду знать! А заодно и пробовать перейти на последнюю версию Node. Просто интересно, что я сталкивался только с тем, что в продакшене используют последнюю Стабильную версию, а для Ноды, получается, можно употреблять и последнюю версию с новыми фичами. Это какая-то особенность ноды, т.е. выпуск стабильных версий с фичами, или это я опять чего-то не знаю?

**Comment by mokevnin** [comment]
Это особенность культуры компании, уровня тестирования, автоматизации, целях. На хекслете мы часто используем даже альфа/бета версии, не говоря уже просто про последние.

**Comment by sollerias** [comment]
Вы имеете в виду особенность культуры Хекслета? Слушайте, интересно тогда получается, что у вас такой уровень внутренних инструментов, знаний, что вы можете себе позволить  так экспериментировать. Это мощно. Хороший пример, которому можно следовать.
